### ISSUE TITLE
Failed to activate the vim-mode-plus-ex-mode package

### ISSUE THREAD

**Issue by lsfa** [t9md/atom-vim-mode-plus-ex-mode#24]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [vim-mode-plus-ex-mode](https://github.com/t9md/atom-vim-mode-plus-ex-mode) package 0.9.0

### Stack Trace

Failed to activate the vim-mode-plus-ex-mode package

```
At Duplicate constructor MoveToLineAndColumn

Error: Duplicate constructor MoveToLineAndColumn
    at Function.Base.extend (/packages/vim-mode-plus/lib/base.coffee:304:17)
    at /packages/vim-mode-plus-ex-mode/lib/main.coffee:44:8
    at Object.consumeVim (/packages/vim-mode-plus-ex-mode/lib/main.coffee:49:19)
    at Provider.module.exports.Provider.provide (/app.asar/node_modules/service-hub/lib/provider.js:34:52)
    at ServiceHub.module.exports.ServiceHub.consume (/app.asar/node_modules/service-hub/lib/service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (/app.asar/src/package.js:404:75)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:221:16)
    at /app.asar/src/package.js:876:25
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:240:20)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:25.9.0 vim-mode-plus:insert-after (input.hidden-input)
     -0:24.2.0 core:backspace (input.hidden-input)
     -0:21.9.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
 14x -0:21.5.0 vim-mode-plus:move-left (input.hidden-input)
     -0:20.3.0 vim-mode-plus:activate-characterwise-visual-mode (input.hidden-input)
 15x -0:20.2.0 vim-mode-plus:move-right (input.hidden-input)
     -0:18.4.0 vim-mode-plus:yank (input.hidden-input)
 15x -0:18.2.0 vim-mode-plus:move-down (input.hidden-input)
     -0:16.3.0 vim-mode-plus:activate-characterwise-visual-mode (input.hidden-input)
     -0:16.1.0 vim-mode-plus:move-to-next-word (input.hidden-input)
     -0:15.9.0 vim-mode-plus:move-left (input.hidden-input)
     -0:15.5.0 vim-mode-plus:put-after (input.hidden-input)
     -0:14.8.0 vim-mode-plus-ex-mode:open (input.hidden-input)
     -0:14.6.0 core:confirm (input.hidden-input)
 12x -0:14.3.0 vim-mode-plus:move-down (input.hidden-input)
 12x -0:12.9.0 vim-mode-plus:move-up (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-shortcuts 0.0.2 
atom-ternjs 0.18.2 
autocomplete-modules 1.6.9 
minimap 4.27.1 
node-debugger 1.10.1 
Remote-FTP 0.10.7 
remote-sync 4.1.5 
vim-mode-plus 0.91.0 
vim-mode-plus-ex-mode 0.9.0 
```

**Comment by glutaminefree** [comment]
Same here!

atom                                - 1.20.1 x64
vim-mode-plus-ex-mode - 0.11.0
OS                                   - Fedora 26 x64

```
service.getClass is not a function
TypeError: service.getClass is not a function
    at Object.consumeVim (/home/glutaminefree/.atom/packages/vim-mode-plus-ex-mode/lib/main.js:46:47)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/usr/share/atom/resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app/src/package.js:454:81)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:256:22)
    at /usr/share/atom/resources/app/src/package.js:968:31
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:246:26)
    at /usr/share/atom/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

**Comment by tj-cs-keita-matsuo** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [vim-mode-plus-ex-mode](https://github.com/t9md/atom-vim-mode-plus-ex-mode) package 0.11.0


### Stack Trace

Failed to activate the vim-mode-plus-ex-mode package

```
At service.getClass is not a function

TypeError: service.getClass is not a function
    at Object.consumeVim (/packages/vim-mode-plus-ex-mode/lib/main.js:46:47)
    at Provider.module.exports.Provider.provide (/private/var/folders/f0/1746zvzd0xz17bygx7dwx7jjr04whv/T/AppTranslocation/935B3053-C5C1-476F-819F-8F494134A9AF/d/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/private/var/folders/f0/1746zvzd0xz17bygx7dwx7jjr04whv/T/AppTranslocation/935B3053-C5C1-476F-819F-8F494134A9AF/d/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (/private/var/folders/f0/1746zvzd0xz17bygx7dwx7jjr04whv/T/AppTranslocation/935B3053-C5C1-476F-819F-8F494134A9AF/d/Atom.app/Contents/Resources/app/src/package.js:454:81)
    at Package.module.exports.Package.activateNow (/private/var/folders/f0/1746zvzd0xz17bygx7dwx7jjr04whv/T/AppTranslocation/935B3053-C5C1-476F-819F-8F494134A9AF/d/Atom.app/Contents/Resources/app/src/package.js:256:22)
    at /private/var/folders/f0/1746zvzd0xz17bygx7dwx7jjr04whv/T/AppTranslocation/935B3053-C5C1-476F-819F-8F494134A9AF/d/Atom.app/Contents/Resources/app/src/package.js:984:31
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/f0/1746zvzd0xz17bygx7dwx7jjr04whv/T/AppTranslocation/935B3053-C5C1-476F-819F-8F494134A9AF/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/f0/1746zvzd0xz17bygx7dwx7jjr04whv/T/AppTranslocation/935B3053-C5C1-476F-819F-8F494134A9AF/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (/private/var/folders/f0/1746zvzd0xz17bygx7dwx7jjr04whv/T/AppTranslocation/935B3053-C5C1-476F-819F-8F494134A9AF/d/Atom.app/Contents/Resources/app/src/command-registry.js:353:24)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/private/var/folders/f0/1746zvzd0xz17bygx7dwx7jjr04whv/T/AppTranslocation/935B3053-C5C1-476F-819F-8F494134A9AF/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/f0/1746zvzd0xz17bygx7dwx7jjr04whv/T/AppTranslocation/935B3053-C5C1-476F-819F-8F494134A9AF/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/f0/1746zvzd0xz17bygx7dwx7jjr04whv/T/AppTranslocation/935B3053-C5C1-476F-819F-8F494134A9AF/d/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/private/var/folders/f0/1746zvzd0xz17bygx7dwx7jjr04whv/T/AppTranslocation/935B3053-C5C1-476F-819F-8F494134A9AF/d/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:38 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -0:36.2.0 core:backspace (input.hidden-input)
     -0:35.4.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:35.3.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:35 vim-mode-plus:move-right (input.hidden-input)
     -0:34.2.0 vim-mode-plus-ex-mode:open (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-keyboard-macros 0.11.0 
autocomplete-elixir 1.5.16 
busy-signal 1.4.3 
docblockr 0.13.4 
emmet 2.4.3 
file-icons 2.1.15 
go-debug 1.5.2 
go-plus 5.7.1 
go-signature-statusbar 1.2.3 
hyperclick 0.1.5 
intentions 1.1.5 
japanese-menu 1.13.0 
language-elixir 0.20.3 
language-elm 1.5.0 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.6.10 
monokai 0.24.0 
project-manager 3.3.5 
qolor 0.4.2 
split-diff 1.5.1 
sync-settings 0.8.3 
vim-mode-plus 1.16.0 
vim-mode-plus-ex-mode 0.11.0 
```

**Comment by t9md** [comment]
update to latest vim-mode-plus
update to latest vim-mode-plus-ex-mode

then restart Atom.
