### ISSUE TITLE
Uncaught TypeError: Cannot read property 'q' of undefined

### ISSUE THREAD

**Issue by gvanderest** [t9md/atom-vim-mode-plus-ex-mode#3]
Had a buffer open (just a normal file) and it didn't close on "q".  This binding should probably also be matched by "bd", as the normal vim implementation of "q" is intended to close the entire editor.

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.4
**Thrown From**: [vim-mode-plus-ex-mode](https://github.com/t9md/atom-vim-mode-plus-ex-mode) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'q' of undefined

```
At /Users/gvanderest/.atom/packages/vim-mode-plus-ex-mode/lib/view.coffee:48

TypeError: Cannot read property 'q' of undefined
  at View.module.exports.View.executeCommand (/Users/gvanderest/.atom/packages/vim-mode-plus-ex-mode/lib/view.coffee:48:33)
  at View.module.exports.View.confirmed (/Users/gvanderest/.atom/packages/vim-mode-plus-ex-mode/lib/view.coffee:124:6)
  at View.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```
### Commands

```
     -0:12.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  4x -0:10.9.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:10.4.0 vim-mode-plus-ex-mode:open (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:10.4.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:09.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.6.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:08.2.0 vim-mode-plus-ex-mode:open (atom-text-editor.editor.vim-mode-plus.normal-mode)
     -0:08.2.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode)
  2x -0:06.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:03.4.0 vim-mode-plus-ex-mode:open (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:03.4.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:02.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 blur (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "followSymlinks": false
  }
}
```
### Installed Packages

``` coffee
# User
jshint, v1.8.3
language-javascript-jsx, v0.3.7
linter, v1.11.3
linter-flake8, v1.13.0
nuclide, v0.124.0
vim-mode-plus, v0.25.0
vim-mode-plus-ex-mode, v0.2.0

# Dev
No dev packages
```

**Comment by t9md** [comment]
I believe this fixed from v0.3.0.
