### ISSUE TITLE
Uncaught TypeError: Cannot read property 'qall' of undefined

### ISSUE THREAD

**Issue by victor-falcon** [t9md/atom-vim-mode-plus-ex-mode#4]
With only one tab opened type :qall and it fails

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11
**Thrown From**: [vim-mode-plus-ex-mode](https://github.com/t9md/atom-vim-mode-plus-ex-mode) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'qall' of undefined

```
At /Users/victorfalcon/.atom/packages/vim-mode-plus-ex-mode/lib/view.coffee:48

TypeError: Cannot read property 'qall' of undefined
    at View.module.exports.View.executeCommand (/Users/victorfalcon/.atom/packages/vim-mode-plus-ex-mode/lib/view.coffee:48:33)
    at View.module.exports.View.confirmed (/Users/victorfalcon/.atom/packages/vim-mode-plus-ex-mode/lib/view.coffee:124:6)
    at View.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:21.6.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:20.7.0 window:focus-pane-on-right (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:20.2.0 window:focus-pane-on-left (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:20.2.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:18.4.0 vim-mode-plus:move-to-next-word (atom-text-editor.editor.vim-mode-plus.visual-mode.characterwise.is-focused)
     -0:17.2.0 core:undo (atom-text-editor.editor.vim-mode-plus.visual-mode.characterwise.is-focused.autocomplete-active)
     -0:16.8.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.visual-mode.characterwise.is-focused)
     -0:16.1.0 core:undo (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:14.8.0 vim-mode-plus:delete (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.characterwise)
  2x -0:11.2.0 core:close (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:05.2.0 blur (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:03.8.0 vim-mode-plus-ex-mode:open (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:03.8.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:02.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.0 blur (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "git-diff",
      "background-tips",
      "open-on-github",
      "welcome",
      "about",
      "autosave",
      "metrics",
      "php-integrator-autocomplete-plus",
      "php-integrator-base",
      "php-integrator-call-tips"
    ],
    "packagesWithKeymapsDisabled": [
      "multi-cursor",
      "highlight-selected"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
advanced-open-file, v0.14.3
atom-sync, v0.6.0
docblockr, v0.7.3
editorconfig, v1.2.4
file-icons, v1.7.1
goto-definition, v1.1.14
highlight-selected, v0.11.2
jquery-snippets, v11.0.0
keyboard-scroll, v0.4.0
phpunit, v1.2.0
pigments, v0.26.0
sync-settings, v0.7.2
typewriter, v0.3.5
vim-mode-plus, v0.32.1
vim-mode-plus-ex-mode, v0.2.0

# Dev
No dev packages
```

**Comment by t9md** [comment]
I believe fixed from v0.3.0
